name: Verify

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:

jobs:
  build:
    name: Verify
    uses: jetty/.github/.github/workflows/maven-ci.yml@main
    with:
      jdk-matrix: '[ "17", "21" ]'