name: Release Drafter
on:
  push:
    branches:
      - master
      
permissions:
  contents: write
  pull-requests: read
  
jobs:
  update_release_draft:
    uses: jetty/.github/.github/workflows/release-drafter.yml@main
